echo off

set arg1=%1

for %%E in (CPI_US,DEFL_US,CPI_NYNJ,DEF_NYNJ,EMP_TOT_NYNJ,EMP_TOT_MANH,EMP_TOT_STATN,EMP_OFF_NYNJ,EMP_OFF_MANH,EMP_OFF_STATN,EMP_TRANS_US,EMP_TRANS_NY,EMP_TRANS_NJ,IMP_US,EXP_US,GDP_US,GDP_US_Real,GDP_NJ,GDP_NJ_Real,GDP_NY,GDP_NY_Real,GDP_NYNJ,GDP_NYNJ_Real,GDP_MANH,GDP_STATN,IP_US,IP_NJ,IP_NY,IP_NYNJ,RETAIL_NYNJ,RETAIL_NYNJ_Real,RETAIL_MANH,RETAIL_MANH_Real,RETAIL_STATN,RETAIL_STATN_Real,HHOLD_NYNJ,HHOLD_MANH,HHOLDSTATN,HHOLD_BERGEN,HHOLD_ESSEX,HHOLD_HUDSON,HHOLD_MIDDLESEX,HHOLD_MONMOUTH,HHOLD_MORRIS,HHOLD_PASSAIC,HHOLD_UNION,HHOLD_ORANGE,HHOLD_ROCKLAND,POP_NYNJ,POP_MANH,POP_STATN,POP_BERGEN,POP_ESSEX,POP_HUDSON,POP_MIDDESEX,POP_MONMOUTH,POP_MORRIS,POP_PASSAIC,POP_UNION,POP_ORANGE,POP_ROCKLAND,MEDHHINC_NYNJ,MEDHHINC_NYNJ_Real,MEDHHINC_MANH,MEDHHINC_MANH_Real,MEDHHINC_STATN,MEDHHINC_STATN_Real,DISPINC_NYNJ,TOTPERSINC_NYNJ,TTPERSINC_NYNJ_Real,TOTPERSINC_MANH,TOTPERSINC_MANH_Real,TOTPERSINC_STATN,TOTPERSINC_STATN_Real,FUEL_EC,FUEL_EC_Real,FUEL_US,FUEL_US_Real,DIESEL,DIESEL_Real) DO (
echo ============================%%E============================
python createRegressInputs.py data\\regress_para\\regresscols_path%arg1%_%%E.xlsx -o data\\regress_data
python regress.py data\\regress_data\\regresscols_path%arg1%_%%E_y.xlsx data\\regress_data\\regresscols_path%arg1%_%%E_x.xlsx data\\regress_out\\regress_summary_path%arg1%_%%E.txt
REM notepad++ data\\regress_out\\regress_summary_path%arg1%_%%E.txt
)